import type { SitePreset } from "./types";

export const krakowPreset: SitePreset = {
  id: "krakow",
  label: "Kraków",
  siteName: "Klimatyzacja Kraków",
  companyLegalName: "Klimatyzacja Kraków Sp. z o.o.",
  siteCity: "Kraków i okolice",
  cityLocative: "w Krakowie",
  siteDefaultUrl: "https://klimatyzacja-krakow.pl",
  email: "kontakt@klimatyzacja-krakow.pl",
  phoneDisplay: "12 345 67 89",
  phoneE164: "+48123456789",
  address: "ul. Karmelicka 12, 31-133 Kraków",
  addressStreet: "ul. Karmelicka 12",
  addressCity: "Kraków",
  addressPostal: "31-133",
  mapsQuery: "ul. Karmelicka 12, Kraków",
  nip: "678-000-00-01",
  regon: "385000001",
  siteTitle: "Klimatyzacja Kraków – montaż i serwis | darmowa wycena",
  siteKeywords: "klimatyzacja Kraków, montaż klimatyzacji, serwis klimatyzacji, klimatyzacja split",
  ogImage: "/gallery/mieszkanie-mokotow.jpg",
  gallery: [
    { image: "/gallery/mieszkanie-mokotow.jpg", alt: "Montaż klimatyzacji split w mieszkaniu na Kazimierzu, Kraków" },
    { image: "/gallery/dom-bielany.jpg", alt: "Jednostki zewnętrzne klimatyzacji na domu w Bronowicach, Kraków" },
    { image: "/gallery/biuro-centrum.jpg", alt: "Klimatyzator ścienny w biurze w centrum Krakowa" },
    { image: "/gallery/apartament-stare-miasto.jpg", alt: "Montaż klimatyzacji w apartamencie na Starym Mieście, Kraków" },
    { image: "/gallery/dom-ursynow.jpg", alt: "Jednostka zewnętrzna klimatyzacji na domu w Podgórzu, Kraków" },
    { image: "/gallery/lokal-wola.jpg", alt: "Klimatyzacja w lokalu usługowym na Krowodrzy, Kraków" },
  ],
  reviews: [
    { name: "Anna K.", text: "Montaż szybki i czysty. Polecam każdemu, kto szuka solidnej firmy w Krakowie." },
    { name: "Marek W.", text: "Bardzo profesjonalna ekipa. Przyjechali na czas, wszystko działa idealnie." },
    { name: "Justyna P.", text: "Najlepsza cena z 5 ofert i super doradztwo przy wyborze modelu." },
    { name: "Tomasz L.", text: "Świetny serwis – po roku zrobili przegląd, wszystko jak nowe." },
    { name: "Karolina M.", text: "Polecam! Konkretni, kulturalni i bardzo szybcy. 5 gwiazdek." },
  ],
};
