import type { SitePreset } from "./types";

export const proklimPreset: SitePreset = {
  id: "proklim",
  label: "PROKLIM",
  siteName: "PROKLIM",
  companyLegalName: "PROKLIM Artur Krychowski",
  siteCity: "Pruszków i Warszawa",
  cityLocative: "w Pruszkowie",
  siteDefaultUrl: "https://proklim.pl",
  email: "kontakt@proklim.pl",
  phoneDisplay: "517 339 359",
  phoneE164: "+48517339359",
  address: "ul. Lipowa 9, 05-800 Pruszków",
  addressStreet: "ul. Lipowa 9",
  addressCity: "Pruszków",
  addressPostal: "05-800",
  mapsQuery: "PROKLIM Artur Krychowski, ul. Lipowa 9, Pruszków",
  nip: "",
  regon: "",
  siteTitle: "PROKLIM – montaż i serwis klimatyzacji Pruszków | rekuperacja",
  siteKeywords:
    "klimatyzacja Pruszków, montaż klimatyzacji Warszawa, serwis klimatyzacji, rekuperacja Pruszków, naprawa klimatyzacji, PROKLIM Artur Krychowski",
  ogImage: "/logo-proklim.png",
  serviceAreas: [
    "Warszawa",
    "Pruszków",
    "Piaseczno",
    "Wołomin",
    "Legionowo",
    "Otwock",
    "Marki",
    "Ząbki",
  ],
  googlePlaceId: "ChIJ51gIKjA1GUcRtxjuF_TBSaA",
  googleReviewsUrl: "https://www.google.com/maps/place/?q=place_id:ChIJ51gIKjA1GUcRtxjuF_TBSaA",
  googleWriteReviewUrl: "https://search.google.com/local/writereview?placeid=ChIJ51gIKjA1GUcRtxjuF_TBSaA",
  gallery: [
    { image: "/gallery/mieszkanie-mokotow.jpg", alt: "Montaż klimatyzacji split w mieszkaniu — realizacja PROKLIM" },
    { image: "/gallery/dom-bielany.jpg", alt: "Jednostki zewnętrzne klimatyzacji na domu — realizacja PROKLIM" },
    { image: "/gallery/biuro-centrum.jpg", alt: "Montaż klimatyzacji w lokalu — realizacja PROKLIM" },
    { image: "/gallery/apartament-stare-miasto.jpg", alt: "Klimatyzacja w apartamencie — realizacja PROKLIM" },
    { image: "/gallery/dom-ursynow.jpg", alt: "Instalacja klimatyzacji na domu jednorodzinnym — PROKLIM" },
    { image: "/gallery/lokal-wola.jpg", alt: "System klimatyzacji w lokalu usługowym — PROKLIM" },
  ],
  reviews: [
    {
      name: "Paweł",
      text: "Szybki montaż, wszystko czysto i profesjonalnie.",
      source: "google",
      rating: 5,
    },
    {
      name: "Michał",
      text: "Najlepsza firma klimatyzacyjna w okolicy. Polecam.",
      source: "google",
      rating: 5,
    },
    {
      name: "Anna",
      text: "Świetny kontakt i szybka realizacja.",
      source: "google",
      rating: 5,
    },
    {
      text: "Szybka i sprawna realizacja. Dobre ceny i estetyczne rozwiązanie.",
      source: "google",
      rating: 5,
    },
    {
      text: "Wszystko działa bez zarzutu.",
      source: "google",
      rating: 5,
    },
    {
      text: "Z czystym sumieniem polecam.",
      source: "google",
      rating: 5,
    },
  ],
};
