import type { SitePreset } from "./types";

export const warszawaPreset: SitePreset = {
  id: "warszawa",
  label: "Warszawa",
  siteName: "Klimatyzacja Warszawa",
  companyLegalName: "Klimatyzacja Warszawa Sp. z o.o.",
  siteCity: "Warszawa i okolice",
  cityLocative: "w Warszawie",
  siteDefaultUrl: "https://klimatyzacja.pl",
  email: "kontakt@klimatyzacja.pl",
  phoneDisplay: "22 357 48 12",
  phoneE164: "+48223574812",
  address: "ul. Puławska 12, 02-566 Warszawa",
  addressStreet: "ul. Puławska 12",
  addressCity: "Warszawa",
  addressPostal: "02-566",
  mapsQuery: "ul. Puławska 12, Warszawa",
  nip: "525-28-00-000",
  regon: "385000000",
  siteTitle: "Klimatyzacja Warszawa – montaż i serwis | darmowa wycena",
  siteKeywords: "klimatyzacja Warszawa, montaż klimatyzacji, serwis klimatyzacji, klimatyzacja split",
  ogImage: "/gallery/mieszkanie-mokotow.jpg",
  gallery: [
    { image: "/gallery/mieszkanie-mokotow.jpg", alt: "Montaż klimatyzacji split w mieszkaniu na Mokotowie, Warszawa" },
    { image: "/gallery/dom-bielany.jpg", alt: "Jednostki zewnętrzne klimatyzacji na domu na Bielanach, Warszawa" },
    { image: "/gallery/biuro-centrum.jpg", alt: "Klimatyzator ścienny w biurze w centrum Warszawy" },
    { image: "/gallery/apartament-stare-miasto.jpg", alt: "Montaż klimatyzacji w apartamencie na Starym Mieście, Warszawa" },
    { image: "/gallery/dom-ursynow.jpg", alt: "Jednostka zewnętrzna klimatyzacji na domu na Ursynowie, Warszawa" },
    { image: "/gallery/lokal-wola.jpg", alt: "Klimatyzacja w lokalu usługowym na Woli, Warszawa" },
  ],
  reviews: [
    { name: "Anna K.", text: "Montaż szybki i czysty. Polecam każdemu, kto szuka solidnej firmy w Warszawie." },
    { name: "Marek W.", text: "Bardzo profesjonalna ekipa. Przyjechali na czas, wszystko działa idealnie." },
    { name: "Justyna P.", text: "Najlepsza cena z 5 ofert i super doradztwo przy wyborze modelu." },
    { name: "Tomasz L.", text: "Świetny serwis – po roku zrobili przegląd, wszystko jak nowe." },
    { name: "Karolina M.", text: "Polecam! Konkretni, kulturalni i bardzo szybcy. 5 gwiazdek." },
  ],
};
