import type { SitePreset } from "./types";

export const wroclawPreset: SitePreset = {
  id: "wroclaw",
  label: "Wrocław",
  siteName: "Klimatyzacja Wrocław",
  companyLegalName: "Klimatyzacja Wrocław Sp. z o.o.",
  siteCity: "Wrocław i okolice",
  cityLocative: "we Wrocławiu",
  siteDefaultUrl: "https://klimatyzacja-wroclaw.pl",
  email: "kontakt@klimatyzacja-wroclaw.pl",
  phoneDisplay: "71 345 67 89",
  phoneE164: "+48713456789",
  address: "ul. Świdnicka 12, 50-023 Wrocław",
  addressStreet: "ul. Świdnicka 12",
  addressCity: "Wrocław",
  addressPostal: "50-023",
  mapsQuery: "ul. Świdnicka 12, Wrocław",
  nip: "899-000-00-02",
  regon: "385000002",
  siteTitle: "Klimatyzacja Wrocław – montaż i serwis | darmowa wycena",
  siteKeywords: "klimatyzacja Wrocław, montaż klimatyzacji, serwis klimatyzacji, klimatyzacja split",
  ogImage: "/gallery/mieszkanie-mokotow.jpg",
  gallery: [
    { image: "/gallery/mieszkanie-mokotow.jpg", alt: "Montaż klimatyzacji split w mieszkaniu na Krzykach, Wrocław" },
    { image: "/gallery/dom-bielany.jpg", alt: "Jednostki zewnętrzne klimatyzacji na domu na Psie Pole, Wrocław" },
    { image: "/gallery/biuro-centrum.jpg", alt: "Klimatyzator ścienny w biurze w centrum Wrocławia" },
    { image: "/gallery/apartament-stare-miasto.jpg", alt: "Montaż klimatyzacji w apartamencie na Starym Mieście, Wrocław" },
    { image: "/gallery/dom-ursynow.jpg", alt: "Jednostka zewnętrzna klimatyzacji na domu na Fabrycznej, Wrocław" },
    { image: "/gallery/lokal-wola.jpg", alt: "Klimatyzacja w lokalu usługowym na Nadodrzu, Wrocław" },
  ],
  reviews: [
    { name: "Anna K.", text: "Montaż szybki i czysty. Polecam każdemu, kto szuka solidnej firmy we Wrocławiu." },
    { name: "Marek W.", text: "Bardzo profesjonalna ekipa. Przyjechali na czas, wszystko działa idealnie." },
    { name: "Justyna P.", text: "Najlepsza cena z 5 ofert i super doradztwo przy wyborze modelu." },
    { name: "Tomasz L.", text: "Świetny serwis – po roku zrobili przegląd, wszystko jak nowe." },
    { name: "Karolina M.", text: "Polecam! Konkretni, kulturalni i bardzo szybcy. 5 gwiazdek." },
  ],
};
